export const WEATHER_GET_START = 'WEATHER/GET/START';
export const WEATHER_GET_FAILED = 'WEATHER/GET/FAILED';
export const WEATHER_GET_SUCESS = 'WEATHER/GET/SUCCESS';
export const CHANGE_CITY = 'CHANGE/CITY';
